import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface Note {
  id: number;
  title: string;
  content: string;
  timestamp: Date;
  isCompleted: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class NotesService {
  private http = inject(HttpClient);
  private apiUrl = 'api/notes'; // Maps to the 'notes' collection in InMemoryDataService

  constructor() { }

  // GET: Fetch all notes from mock DB
  getNotes(): Observable<Note[]> {
    return this.http.get<Note[]>(this.apiUrl);
  }

  // POST: Add a new note
  addNote(title: string, content: string): Observable<Note> {
    const newNote = {
      title,
      content,
      timestamp: new Date(),
      isCompleted: false
    } as Note; 
    // ID is auto-generated by the Mock DB
    return this.http.post<Note>(this.apiUrl, newNote);
  }

  // PUT: Update an existing note
  updateNote(note: Note): Observable<any> {
    return this.http.put(this.apiUrl, note);
  }

  // Helper for toggling completion
  toggleComplete(note: Note): Observable<any> {
    // Create a copy with the status flipped
    const updatedNote = { ...note, isCompleted: !note.isCompleted };
    return this.http.put(this.apiUrl, updatedNote);
  }

  // DELETE: Delete a note by ID
  deleteNote(id: number): Observable<any> {
    const url = `${this.apiUrl}/${id}`;
    return this.http.delete(url);
  }
}